name: GUD
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.73
  - blas=1.0
  - mysql-connector-c=6.1.11
  - mysql-connector-python=8.0.16
  - mysqlclient=1.3.14
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1
  - pandas=0.25.3
  - parallel
  - pip=19.1.1
  - python=3.7.3
  - pymysql=0.9.3
  - readline=7.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlalchemy=1.3.4
  - sqlite=3.28.0
  - tk=8.6.8
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - click==7.0
    - configparser==3.7.4
    - cython==0.29.10
    - datetime==4.3
    - flask==1.0.3
    - fuzzywuzzy==0.17.0
    - importlib-metadata==0.18
    - interval-binning==1.0.0
    - isort==4.3.20
    - jinja2==2.10.1
    - lazy-object-proxy==1.4.1
    - lxml==4.3.4
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - more-itertools==7.1.0
    - packaging==19.0
    - py==1.8.0
    - pycodestyle==2.5.0
    - pylint==2.3.1
    - pyparsing==2.4.0
    - pytest==5.0.0
    - python-Levenshtein==0.12.0
    - simplejson==3.16.0
    - sqlalchemy-fulltext-search==0.2.5
    - sqlalchemy-utils==0.34.0
    - werkzeug==0.15.4